let products = [
    {
        name: 'Батон нарезной',
        proteins: 7.5,
        fats: 2.9,
        carbohydrates: 51.4,
        calories: 262,
        category: 'Зерновые продукты',
    },
    {
        name: 'Гречиха (зерно)',
        proteins: 10.8,
        fats: 3.2,
        carbohydrates: 56,
        calories: 296,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша гречневая (из крупы ядрица)',
        proteins: 4,
        fats: 1.1,
        carbohydrates: 14.6,
        calories: 101,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша из овсяных хлопьев Геркулес',
        proteins: 2.4,
        fats: 4,
        carbohydrates: 14.8,
        calories: 105,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша манная',
        proteins: 2.2,
        fats: 2.9,
        carbohydrates: 16.4,
        calories: 100,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша овсяная',
        proteins: 2.6,
        fats: 4.1,
        carbohydrates: 15.5,
        calories: 109,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша перловая',
        proteins: 2.9,
        fats: 3.5,
        carbohydrates: 22.9,
        calories: 135,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша пшеничная',
        proteins: 4.4,
        fats: 3.6,
        carbohydrates: 25.7,
        calories: 153,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша пшенная',
        proteins: 2.8,
        fats: 3.4,
        carbohydrates: 16.8,
        calories: 109,
        category: 'Зерновые продукты',
    },
    {
        name: 'Каша рисовая',
        proteins: 2.4,
        fats: 3.5,
        carbohydrates: 25.8,
        calories: 144,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа гречневая (продел)',
        proteins: 9.5,
        fats: 2.3,
        carbohydrates: 60.4,
        calories: 300,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа гречневая (ядрица)',
        proteins: 12.6,
        fats: 3.3,
        carbohydrates: 57.1,
        calories: 308,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа кукурузная',
        proteins: 8.3,
        fats: 1.2,
        carbohydrates: 71,
        calories: 328,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа манная',
        proteins: 10.3,
        fats: 1,
        carbohydrates: 70.6,
        calories: 333,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа овсяная',
        proteins: 12.3,
        fats: 6.1,
        carbohydrates: 59.5,
        calories: 342,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа перловая',
        proteins: 9.3,
        fats: 1.1,
        carbohydrates: 66.9,
        calories: 315,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа пшеничная',
        proteins: 11,
        fats: 1.2,
        carbohydrates: 68.5,
        calories: 329,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа пшено (шлифованное)',
        proteins: 11.5,
        fats: 3.3,
        carbohydrates: 66.5,
        calories: 342,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа рисовая',
        proteins: 7,
        fats: 1,
        carbohydrates: 74,
        calories: 333,
        category: 'Зерновые продукты',
    },
    {
        name: 'Крупа ячневая',
        proteins: 10,
        fats: 1.3,
        carbohydrates: 65.4,
        calories: 313,
        category: 'Зерновые продукты',
    },
    {
        name: 'Кукуруза консервированная',
        proteins: 2.2,
        fats: 0.4,
        carbohydrates: 11.2,
        calories: 58,
        category: 'Зерновые продукты',
    },
    {
        name: 'Кукуруза сладкая',
        proteins: 3.2,
        fats: 1.2,
        carbohydrates: 19,
        calories: 86,
        category: 'Зерновые продукты',
    },
    {
        name: 'Макароны из муки 1 сорта',
        proteins: 11.2,
        fats: 1.6,
        carbohydrates: 68.4,
        calories: 333,
        category: 'Зерновые продукты',
    },
    {
        name: 'Макароны из муки в/с',
        proteins: 11,
        fats: 1.3,
        carbohydrates: 70.5,
        calories: 338,
        category: 'Зерновые продукты',
    },
    {
        name: 'Макароны отварные',
        proteins: 3.6,
        fats: 0.4,
        carbohydrates: 20,
        calories: 98,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука гречневая',
        proteins: 12.6,
        fats: 3.1,
        carbohydrates: 70.6,
        calories: 335,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука кукурузная',
        proteins: 7.2,
        fats: 1.5,
        carbohydrates: 72.1,
        calories: 331,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука овсяная',
        proteins: 13,
        fats: 6.8,
        carbohydrates: 64.9,
        calories: 369,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука овсяная (толокно)',
        proteins: 12.5,
        fats: 6,
        carbohydrates: 64.9,
        calories: 363,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука пшеничная 1 сорта',
        proteins: 11.1,
        fats: 1.5,
        carbohydrates: 67.8,
        calories: 329,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука пшеничная 2 сорта',
        proteins: 11.6,
        fats: 1.8,
        carbohydrates: 64.8,
        calories: 322,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука пшеничная в/с',
        proteins: 10.8,
        fats: 1.3,
        carbohydrates: 69.9,
        calories: 334,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука пшеничная обойная',
        proteins: 11.5,
        fats: 2.2,
        carbohydrates: 61.5,
        calories: 312,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука ржаная обдирная',
        proteins: 8.9,
        fats: 1.7,
        carbohydrates: 61.8,
        calories: 298,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука ржаная обойная',
        proteins: 10.7,
        fats: 1.9,
        carbohydrates: 58.5,
        calories: 294,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука ржаная сеяная',
        proteins: 6.9,
        fats: 1.4,
        carbohydrates: 66.3,
        calories: 305,
        category: 'Зерновые продукты',
    },
    {
        name: 'Мука рисовая',
        proteins: 7.4,
        fats: 0.6,
        carbohydrates: 80.2,
        calories: 356,
        category: 'Зерновые продукты',
    },
    {
        name: 'Овёс (зерно)',
        proteins: 10,
        fats: 6.2,
        carbohydrates: 55.1,
        calories: 316,
        category: 'Зерновые продукты',
    },
    {
        name: 'Оладьи',
        proteins: 6.5,
        fats: 6.6,
        carbohydrates: 31.6,
        calories: 213,
        category: 'Зерновые продукты',
    },
    {
        name: 'Отруби овсяные',
        proteins: 17.3,
        fats: 7,
        carbohydrates: 66.2,
        calories: 246,
        category: 'Зерновые продукты',
    },
    {
        name: 'Отруби пшеничные',
        proteins: 16,
        fats: 3.8,
        carbohydrates: 16.6,
        calories: 165,
        category: 'Зерновые продукты',
    },
    {
        name: 'Печенье сахарное',
        proteins: 7.5,
        fats: 9.8,
        carbohydrates: 74.4,
        calories: 417,
        category: 'Зерновые продукты',
    },
    {
        name: 'Печенье сдобное',
        proteins: 6.4,
        fats: 16.8,
        carbohydrates: 68.5,
        calories: 451,
        category: 'Зерновые продукты',
    },
    {
        name: 'Пряники заварные',
        proteins: 5.9,
        fats: 4.7,
        carbohydrates: 75,
        calories: 366,
        category: 'Зерновые продукты',
    },
    {
        name: 'Пшеница (зерно, мягкий сорт)',
        proteins: 11.8,
        fats: 2.2,
        carbohydrates: 59.5,
        calories: 305,
        category: 'Зерновые продукты',
    },
    {
        name: 'Пшеница (зерно, твердый сорт)',
        proteins: 13,
        fats: 2.5,
        carbohydrates: 57.5,
        calories: 304,
        category: 'Зерновые продукты',
    },
    {
        name: 'Рис (зерно)',
        proteins: 7.5,
        fats: 2.6,
        carbohydrates: 62.3,
        calories: 303,
        category: 'Зерновые продукты',
    },
    {
        name: 'Рожь (зерно)',
        proteins: 9.9,
        fats: 2.2,
        carbohydrates: 55.8,
        calories: 283,
        category: 'Зерновые продукты',
    },
    {
        name: 'Сухари сливочные',
        proteins: 8.5,
        fats: 10.8,
        carbohydrates: 66.7,
        calories: 399,
        category: 'Зерновые продукты',
    },
    {
        name: 'Сушки простые',
        proteins: 10.7,
        fats: 1.2,
        carbohydrates: 71.2,
        calories: 339,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлеб бородинский',
        proteins: 6.8,
        fats: 1.3,
        carbohydrates: 39.8,
        calories: 201,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлеб пшеничный (из муки 1 сорта)',
        proteins: 7.9,
        fats: 1,
        carbohydrates: 48.3,
        calories: 235,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлеб пшеничный (из муки в/с)',
        proteins: 7.6,
        fats: 0,
        carbohydrates: 49.2,
        calories: 235,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлеб пшеничный (из обойной муки)',
        proteins: 6.6,
        fats: 1.2,
        carbohydrates: 33.4,
        calories: 174,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлеб рижский',
        proteins: 5.6,
        fats: 1.1,
        carbohydrates: 49.4,
        calories: 232,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлеб цельнозерновой',
        proteins: 13,
        fats: 3.4,
        carbohydrates: 41.3,
        calories: 247,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлебцы с отрубями',
        proteins: 8.2,
        fats: 2.6,
        carbohydrates: 46.3,
        calories: 242,
        category: 'Зерновые продукты',
    },
    {
        name: 'Хлопья овсяные "Геркулес"',
        proteins: 12.3,
        fats: 6.2,
        carbohydrates: 61.8,
        calories: 352,
        category: 'Зерновые продукты',
    },
    {
        name: 'Ячмень (зерно)',
        proteins: 10.3,
        fats: 2.4,
        carbohydrates: 56.4,
        calories: 288,
        category: 'Зерновые продукты',
    },
    {
        name: 'Ацидофилин 1%',
        proteins: 3,
        fats: 1,
        carbohydrates: 4,
        calories: 40,
        category: 'Молочные продукты',
    },
    {
        name: 'Ацидофилин 3,2%',
        proteins: 2.9,
        fats: 3.2,
        carbohydrates: 3.8,
        calories: 59,
        category: 'Молочные продукты',
    },
    {
        name: 'Ацидофилин 3,2% сладкий',
        proteins: 2.8,
        fats: 3.2,
        carbohydrates: 8.6,
        calories: 77,
        category: 'Молочные продукты',
    },
    {
        name: 'Ацидофилин нежирный',
        proteins: 3,
        fats: 0.05,
        carbohydrates: 3.9,
        calories: 31,
        category: 'Молочные продукты',
    },
    {
        name: 'Брынза (из коровьего молока)',
        proteins: 22.1,
        fats: 19.2,
        carbohydrates: 0.4,
        calories: 262,
        category: 'Молочные продукты',
    },
    {
        name: 'Варенец 2,5%',
        proteins: 2.9,
        fats: 2.5,
        carbohydrates: 4.1,
        calories: 53,
        category: 'Молочные продукты',
    },
    {
        name: 'Запеканка из обезжиренного творога',
        proteins: 17.6,
        fats: 4.2,
        carbohydrates: 14.2,
        calories: 168,
        category: 'Молочные продукты',
    },
    {
        name: 'Йогурт 1,5%',
        proteins: 4.1,
        fats: 1.5,
        carbohydrates: 5.9,
        calories: 57,
        category: 'Молочные продукты',
    },
    {
        name: 'Йогурт 1,5% плодово-ягодный',
        proteins: 4,
        fats: 1.5,
        carbohydrates: 14.3,
        calories: 90,
        category: 'Молочные продукты',
    },
    {
        name: 'Йогурт 3,2%',
        proteins: 5,
        fats: 3.2,
        carbohydrates: 3.5,
        calories: 68,
        category: 'Молочные продукты',
    },
    {
        name: 'Йогурт 3,2% сладкий',
        proteins: 5,
        fats: 3.2,
        carbohydrates: 8.5,
        calories: 87,
        category: 'Молочные продукты',
    },
    {
        name: 'Йогурт 6%',
        proteins: 5,
        fats: 6,
        carbohydrates: 3.5,
        calories: 92,
        category: 'Молочные продукты',
    },
    {
        name: 'Йогурт 6% сладкий',
        proteins: 5,
        fats: 6,
        carbohydrates: 8.5,
        calories: 112,
        category: 'Молочные продукты',
    },
    {
        name: 'Кефир 1%',
        proteins: 3,
        fats: 1,
        carbohydrates: 4,
        calories: 40,
        category: 'Молочные продукты',
    },
    {
        name: 'Кефир 2,5%',
        proteins: 2.9,
        fats: 2.5,
        carbohydrates: 4,
        calories: 53,
        category: 'Молочные продукты',
    },
    {
        name: 'Кефир 3,2%',
        proteins: 2.9,
        fats: 3.2,
        carbohydrates: 4,
        calories: 59,
        category: 'Молочные продукты',
    },
    {
        name: 'Кефир нежирный',
        proteins: 3,
        fats: 0.05,
        carbohydrates: 4,
        calories: 31,
        category: 'Молочные продукты',
    },
    {
        name: 'Кумыс (из кобыльего молока)',
        proteins: 2.1,
        fats: 1.9,
        carbohydrates: 5,
        calories: 50,
        category: 'Молочные продукты',
    },
    {
        name: 'Кумыс нежирный (из коровьего молока)',
        proteins: 3,
        fats: 0.05,
        carbohydrates: 6.3,
        calories: 41,
        category: 'Молочные продукты',
    },
    {
        name: 'Масса творожная 16,5% жирности',
        proteins: 12,
        fats: 16.5,
        carbohydrates: 9.5,
        calories: 232,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко 1,5%',
        proteins: 3,
        fats: 1.5,
        carbohydrates: 4.8,
        calories: 45,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко 2,5%',
        proteins: 2.9,
        fats: 2.5,
        carbohydrates: 4.8,
        calories: 54,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко 3,2%',
        proteins: 2.9,
        fats: 3.2,
        carbohydrates: 4.7,
        calories: 60,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко 3,5%',
        proteins: 2.9,
        fats: 3.5,
        carbohydrates: 4.7,
        calories: 62,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко козье',
        proteins: 3.6,
        fats: 4.1,
        carbohydrates: 4.5,
        calories: 69,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко нежирное',
        proteins: 3,
        fats: 0.05,
        carbohydrates: 4.9,
        calories: 32,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко сгущённое с сахаром 5%',
        proteins: 7.1,
        fats: 5,
        carbohydrates: 55.2,
        calories: 295,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко сгущённое с сахаром 8,5%',
        proteins: 7.2,
        fats: 8.5,
        carbohydrates: 55.5,
        calories: 328,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко сгущённое с сахаром нежирное',
        proteins: 7.5,
        fats: 0.2,
        carbohydrates: 56.8,
        calories: 259,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко сухое 15%',
        proteins: 28.5,
        fats: 15,
        carbohydrates: 44.7,
        calories: 432,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко сухое 25%',
        proteins: 24.2,
        fats: 25,
        carbohydrates: 39.3,
        calories: 483,
        category: 'Молочные продукты',
    },
    {
        name: 'Молоко сухое нежирное',
        proteins: 33.2,
        fats: 1,
        carbohydrates: 52.6,
        calories: 362,
        category: 'Молочные продукты',
    },
    {
        name: 'Мороженое пломбир',
        proteins: 3.7,
        fats: 15,
        carbohydrates: 20.4,
        calories: 232,
        category: 'Молочные продукты',
    },
    {
        name: 'Мороженое сливочное',
        proteins: 3.3,
        fats: 10,
        carbohydrates: 19.4,
        calories: 183,
        category: 'Молочные продукты',
    },
    {
        name: 'Пахта',
        proteins: 3.3,
        fats: 1,
        carbohydrates: 4.7,
        calories: 41,
        category: 'Молочные продукты',
    },
    {
        name: 'Простокваша 1%',
        proteins: 3,
        fats: 1,
        carbohydrates: 4.1,
        calories: 40,
        category: 'Молочные продукты',
    },
    {
        name: 'Простокваша 2,5%',
        proteins: 2.9,
        fats: 2.5,
        carbohydrates: 4.1,
        calories: 53,
        category: 'Молочные продукты',
    },
    {
        name: 'Простокваша 3,2%',
        proteins: 2.9,
        fats: 3.2,
        carbohydrates: 4.1,
        calories: 59,
        category: 'Молочные продукты',
    },
    {
        name: 'Простокваша нежирная',
        proteins: 3,
        fats: 0.05,
        carbohydrates: 3.8,
        calories: 30,
        category: 'Молочные продукты',
    },
    {
        name: 'Ряженка 1%',
        proteins: 3,
        fats: 1,
        carbohydrates: 4.2,
        calories: 40,
        category: 'Молочные продукты',
    },
    {
        name: 'Ряженка 2,5%',
        proteins: 2.9,
        fats: 2.5,
        carbohydrates: 4.2,
        calories: 54,
        category: 'Молочные продукты',
    },
    {
        name: 'Ряженка 4%',
        proteins: 2.8,
        fats: 4,
        carbohydrates: 4.2,
        calories: 67,
        category: 'Молочные продукты',
    },
    {
        name: 'Ряженка 6%',
        proteins: 3,
        fats: 6,
        carbohydrates: 4.1,
        calories: 85,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки 10%',
        proteins: 2.7,
        fats: 10,
        carbohydrates: 4.5,
        calories: 119,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки 20%',
        proteins: 2.5,
        fats: 20,
        carbohydrates: 4,
        calories: 207,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки 25%',
        proteins: 2.4,
        fats: 25,
        carbohydrates: 3.9,
        calories: 251,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки 35%',
        proteins: 2.2,
        fats: 35,
        carbohydrates: 3.2,
        calories: 337,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки 8%',
        proteins: 2.8,
        fats: 8,
        carbohydrates: 4.5,
        calories: 102,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки сгущённые с сахаром 19%',
        proteins: 8,
        fats: 19,
        carbohydrates: 47,
        calories: 392,
        category: 'Молочные продукты',
    },
    {
        name: 'Сливки сухие 42%',
        proteins: 19,
        fats: 42,
        carbohydrates: 30.2,
        calories: 577,
        category: 'Молочные продукты',
    },
    {
        name: 'Сметана 10%',
        proteins: 2.7,
        fats: 10,
        carbohydrates: 3.9,
        calories: 119,
        category: 'Молочные продукты',
    },
    {
        name: 'Сметана 15%',
        proteins: 2.6,
        fats: 15,
        carbohydrates: 3.6,
        calories: 162,
        category: 'Молочные продукты',
    },
    {
        name: 'Сметана 20%',
        proteins: 2.5,
        fats: 20,
        carbohydrates: 3.4,
        calories: 206,
        category: 'Молочные продукты',
    },
    {
        name: 'Сметана 25%',
        proteins: 2.4,
        fats: 25,
        carbohydrates: 3.2,
        calories: 250,
        category: 'Молочные продукты',
    },
    {
        name: 'Сметана 30%',
        proteins: 2.3,
        fats: 30,
        carbohydrates: 3.1,
        calories: 293,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Адыгейский"',
        proteins: 19.8,
        fats: 19.8,
        carbohydrates: 1.5,
        calories: 264,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Голландский" 45%',
        proteins: 26.3,
        fats: 26.6,
        carbohydrates: 0,
        calories: 350,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Камамбер"',
        proteins: 15.3,
        fats: 28.8,
        carbohydrates: 0.1,
        calories: 324,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Пармезан"',
        proteins: 35.7,
        fats: 25.8,
        carbohydrates: 0.8,
        calories: 392,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Пошехонский" 45%',
        proteins: 26,
        fats: 26.1,
        carbohydrates: 0,
        calories: 344,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Рокфор" 50%',
        proteins: 20.5,
        fats: 27.5,
        carbohydrates: 0,
        calories: 335,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Российский" 50%',
        proteins: 23.2,
        fats: 29.5,
        carbohydrates: 0,
        calories: 364,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Сулугуни"',
        proteins: 20.5,
        fats: 22,
        carbohydrates: 0.4,
        calories: 286,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Фета"',
        proteins: 14.2,
        fats: 21.3,
        carbohydrates: 4.1,
        calories: 264,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Чеддер" 50%',
        proteins: 23.5,
        fats: 30.8,
        carbohydrates: 0,
        calories: 380,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр "Швейцарский" 50%',
        proteins: 24.6,
        fats: 31.6,
        carbohydrates: 0,
        calories: 391,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр Гауда',
        proteins: 24.9,
        fats: 27.4,
        carbohydrates: 2.2,
        calories: 356,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр нежирный',
        proteins: 18,
        fats: 0.6,
        carbohydrates: 1.5,
        calories: 86,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр плавленый "Колбасный"',
        proteins: 21.2,
        fats: 19.4,
        carbohydrates: 3.7,
        calories: 275,
        category: 'Молочные продукты',
    },
    {
        name: 'Сыр плавленый "Российский"',
        proteins: 20.5,
        fats: 23,
        carbohydrates: 2.5,
        calories: 300,
        category: 'Молочные продукты',
    },
    {
        name: 'Сырки глазированные 27,7% жирности',
        proteins: 7.9,
        fats: 27.7,
        carbohydrates: 32.6,
        calories: 413,
        category: 'Молочные продукты',
    },
    {
        name: 'Сырники из обезжиренного творога',
        proteins: 18.6,
        fats: 3.6,
        carbohydrates: 18.2,
        calories: 183,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог 11%',
        proteins: 16,
        fats: 11,
        carbohydrates: 3,
        calories: 178,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог 18% (жирный)',
        proteins: 15,
        fats: 18,
        carbohydrates: 2.8,
        calories: 236,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог 2%',
        proteins: 20,
        fats: 2,
        carbohydrates: 3,
        calories: 114,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог 4%',
        proteins: 21,
        fats: 4,
        carbohydrates: 3,
        calories: 136,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог 5%',
        proteins: 21,
        fats: 5,
        carbohydrates: 3,
        calories: 145,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог 9% (полужирный)',
        proteins: 18,
        fats: 9,
        carbohydrates: 3,
        calories: 169,
        category: 'Молочные продукты',
    },
    {
        name: 'Творог нежирный',
        proteins: 22,
        fats: 0.6,
        carbohydrates: 3.3,
        calories: 110,
        category: 'Молочные продукты',
    },
    {
        name: 'Белок куриного яйца',
        proteins: 11.1,
        fats: 0,
        carbohydrates: 1,
        calories: 48,
        category: 'Яйца и яйцепродукты',
    },
    {
        name: 'Желток куриного яйца',
        proteins: 16.2,
        fats: 31.2,
        carbohydrates: 0,
        calories: 354,
        category: 'Яйца и яйцепродукты',
    },
    {
        name: 'Яичный порошок',
        proteins: 46,
        fats: 37.3,
        carbohydrates: 4.5,
        calories: 542,
        category: 'Яйца и яйцепродукты',
    },
    {
        name: 'Яйцо куриное',
        proteins: 12.7,
        fats: 11.5,
        carbohydrates: 0.7,
        calories: 157,
        category: 'Яйца и яйцепродукты',
    },
    {
        name: 'Яйцо перепелиное',
        proteins: 11.9,
        fats: 13.1,
        carbohydrates: 0.6,
        calories: 168,
        category: 'Яйца и яйцепродукты',
    },
    {
        name: 'Вобла',
        proteins: 18,
        fats: 2.8,
        carbohydrates: 0,
        calories: 95,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Горбуша',
        proteins: 20.5,
        fats: 6.5,
        carbohydrates: 0,
        calories: 140,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Горбуша натуральная (консервы)',
        proteins: 20.9,
        fats: 5.8,
        carbohydrates: 0,
        calories: 136,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Икра красная зернистая',
        proteins: 31.5,
        fats: 13.2,
        carbohydrates: 1,
        calories: 249,
        category: 'Рыба и морепродукты',
    },{
        name: 'Икра минтая',
        proteins: 27.9,
        fats: 1.8,
        carbohydrates: 1.1,
        calories: 132,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Икра чёрная зернистая',
        proteins: 26.8,
        fats: 13.8,
        carbohydrates: 0.8,
        calories: 235,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Кальмар',
        proteins: 18,
        fats: 2.2,
        carbohydrates: 2,
        calories: 100,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Камбала',
        proteins: 15.7,
        fats: 3,
        carbohydrates: 0,
        calories: 90,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Кета',
        proteins: 19,
        fats: 5.6,
        carbohydrates: 0,
        calories: 127,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Килька балтийская',
        proteins: 14.1,
        fats: 9,
        carbohydrates: 0,
        calories: 137,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Килька каспийская',
        proteins: 18.5,
        fats: 13.1,
        carbohydrates: 0,
        calories: 192,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Креветка',
        proteins: 20.5,
        fats: 1.6,
        carbohydrates: 0.3,
        calories: 98,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Лещ',
        proteins: 17.1,
        fats: 4.4,
        carbohydrates: 0,
        calories: 105,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Лосось атлантический (сёмга)',
        proteins: 20,
        fats: 8.1,
        carbohydrates: 0,
        calories: 153,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Мидии',
        proteins: 11.5,
        fats: 2,
        carbohydrates: 3.3,
        calories: 77,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Минтай',
        proteins: 15.9,
        fats: 0.9,
        carbohydrates: 0,
        calories: 72,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Мойва',
        proteins: 13.4,
        fats: 12.6,
        carbohydrates: 0,
        calories: 166,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Навага',
        proteins: 19.2,
        fats: 1.6,
        carbohydrates: 0,
        calories: 91,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Окунь морской',
        proteins: 18.2,
        fats: 3.3,
        carbohydrates: 0,
        calories: 103,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Окунь речной',
        proteins: 18.5,
        fats: 0.9,
        carbohydrates: 0,
        calories: 82,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Осётр',
        proteins: 16.4,
        fats: 10.9,
        carbohydrates: 0,
        calories: 164,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Палтус',
        proteins: 18.9,
        fats: 3,
        carbohydrates: 0,
        calories: 103,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Печень трески (консервы)',
        proteins: 4.2,
        fats: 65.7,
        carbohydrates: 1.2,
        calories: 613,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Пикша',
        proteins: 17.2,
        fats: 0.5,
        carbohydrates: 0,
        calories: 73,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Рак речной',
        proteins: 15.5,
        fats: 1,
        carbohydrates: 1.2,
        calories: 76,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Рыбий жир (из печени трески)',
        proteins: 0,
        fats: 99.8,
        carbohydrates: 0,
        calories: 898,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Сазан',
        proteins: 18.2,
        fats: 2.7,
        carbohydrates: 0,
        calories: 97,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Салака',
        proteins: 17,
        fats: 6.3,
        carbohydrates: 0,
        calories: 125,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Сельдь жирная',
        proteins: 17.7,
        fats: 19.5,
        carbohydrates: 0,
        calories: 248,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Сельдь нежирная',
        proteins: 19.1,
        fats: 6.5,
        carbohydrates: 0,
        calories: 135,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Сельдь среднесолёная',
        proteins: 17,
        fats: 8.5,
        carbohydrates: 0,
        calories: 145,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Скумбрия',
        proteins: 18,
        fats: 13.2,
        carbohydrates: 0,
        calories: 191,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Скумбрия в масле (консервы)',
        proteins: 14.4,
        fats: 28.9,
        carbohydrates: 0,
        calories: 318,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Сом',
        proteins: 17.2,
        fats: 5.1,
        carbohydrates: 0,
        calories: 115,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Ставрида',
        proteins: 18.5,
        fats: 4.5,
        carbohydrates: 0,
        calories: 114,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Судак',
        proteins: 18.4,
        fats: 1.1,
        carbohydrates: 0,
        calories: 84,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Треска',
        proteins: 16,
        fats: 0.6,
        carbohydrates: 0,
        calories: 69,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Тунец',
        proteins: 24.4,
        fats: 4.6,
        carbohydrates: 0,
        calories: 139,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Угорь',
        proteins: 14.5,
        fats: 30.5,
        carbohydrates: 0,
        calories: 333,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Устрица',
        proteins: 9,
        fats: 2,
        carbohydrates: 4.5,
        calories: 72,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Хек',
        proteins: 16.6,
        fats: 2.2,
        carbohydrates: 0,
        calories: 86,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Шпроты в масле (консервы)',
        proteins: 17.4,
        fats: 32.4,
        carbohydrates: 0,
        calories: 363,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Щука',
        proteins: 18.4,
        fats: 1.1,
        carbohydrates: 0,
        calories: 84,
        category: 'Рыба и морепродукты',
    },
    {
        name: 'Горох (лущеный)',
        proteins: 23,
        fats: 1.6,
        carbohydrates: 48.1,
        calories: 299,
        category: 'Бобовые',
    },
    {
        name: 'Горох зелёный (свежий)',
        proteins: 5,
        fats: 0.2,
        carbohydrates: 8.3,
        calories: 55,
        category: 'Бобовые',
    },
    {
        name: 'Зелёный горошек (консервы)',
        proteins: 3.1,
        fats: 0.2,
        carbohydrates: 6.5,
        calories: 40,
        category: 'Бобовые',
    },{
        name: 'Маш',
        proteins: 23.5,
        fats: 2,
        carbohydrates: 46,
        calories: 300,
        category: 'Бобовые',
    },
    {
        name: 'Нут',
        proteins: 20.1,
        fats: 4.3,
        carbohydrates: 46.1,
        calories: 309,
        category: 'Бобовые',
    },
    {
        name: 'Соя (зерно)',
        proteins: 34.9,
        fats: 17.3,
        carbohydrates: 17.3,
        calories: 364,
        category: 'Бобовые',
    },
    {
        name: 'Суп фасолевый',
        proteins: 3,
        fats: 1.3,
        carbohydrates: 6.9,
        calories: 54,
        category: 'Бобовые',
    },
    {
        name: 'Фасоль (зерно)',
        proteins: 21,
        fats: 2,
        carbohydrates: 47,
        calories: 298,
        category: 'Бобовые',
    },
    {
        name: 'Фасоль (стручковая)',
        proteins: 2.5,
        fats: 0.3,
        carbohydrates: 3,
        calories: 23,
        category: 'Бобовые',
    },
    {
        name: 'Чечевица (зерно)',
        proteins: 24,
        fats: 1.5,
        carbohydrates: 46.3,
        calories: 295,
        category: 'Бобовые',
    },
    {
        name: 'Арахис',
        proteins: 26.3,
        fats: 45.2,
        carbohydrates: 9.9,
        calories: 552,
        category: 'Орехи и семена',
    },
    {
        name: 'Грецкий орех',
        proteins: 16.2,
        fats: 60.8,
        carbohydrates: 11.1,
        calories: 656,
        category: 'Орехи и семена',
    },
    {
        name: 'Желуди сушёные',
        proteins: 8.1,
        fats: 31.4,
        carbohydrates: 53.6,
        calories: 509,
        category: 'Орехи и семена',
    },
    {
        name: 'Кедровый орех',
        proteins: 13.7,
        fats: 68.4,
        carbohydrates: 13.1,
        calories: 875,
        category: 'Орехи и семена',
    },
    {
        name: 'Кешью',
        proteins: 18.5,
        fats: 48.5,
        carbohydrates: 22.5,
        calories: 600,
        category: 'Орехи и семена',
    },
    {
        name: 'Кунжут',
        proteins: 19.4,
        fats: 48.7,
        carbohydrates: 12.2,
        calories: 565,
        category: 'Орехи и семена',
    },
    {
        name: 'Миндаль',
        proteins: 18.6,
        fats: 53.7,
        carbohydrates: 13,
        calories: 609,
        category: 'Орехи и семена',
    },
    {
        name: 'Семена подсолнечника (семечки)',
        proteins: 20.7,
        fats: 52.9,
        carbohydrates: 10.5,
        calories: 601,
        category: 'Орехи и семена',
    },
    {
        name: 'Фисташки',
        proteins: 20.2,
        fats: 45.3,
        carbohydrates: 27.2,
        calories: 560,
        category: 'Орехи и семена',
    },
    {
        name: 'Фундук',
        proteins: 13,
        fats: 62.6,
        carbohydrates: 9.3,
        calories: 653,
        category: 'Орехи и семена',
    },
    {
        name: 'Базилик (зелень)',
        proteins: 3.2,
        fats: 0.6,
        carbohydrates: 2.7,
        calories: 23,
        category: 'Овощи и зелень',
    },
    {
        name: 'Баклажаны',
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 4.5,
        calories: 24,
        category: 'Овощи и зелень',
    },
    {
        name: 'Брюква',
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 7.7,
        calories: 37,
        category: 'Овощи и зелень',
    },
    {
        name: 'Запеканка картофельная',
        proteins: 3,
        fats: 5.9,
        carbohydrates: 17.5,
        calories: 136,
        category: 'Овощи и зелень',
    },
    {
        name: 'Икра из баклажанов (консервы)',
        proteins: 1.7,
        fats: 13.3,
        carbohydrates: 5.1,
        calories: 148,
        category: 'Овощи и зелень',
    },
    {
        name: 'Икра кабачковая (консервы)',
        proteins: 1.9,
        fats: 8.9,
        carbohydrates: 7.7,
        calories: 119,
        category: 'Овощи и зелень',
    },
    {
        name: 'Имбирь (корень)',
        proteins: 1.8,
        fats: 0.8,
        carbohydrates: 17.8,
        calories: 80,
        category: 'Овощи и зелень',
    },
    {
        name: 'Кабачки',
        proteins: 0.6,
        fats: 0.3,
        carbohydrates: 4.6,
        calories: 24,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста белокочанная',
        proteins: 1.8,
        fats: 0.1,
        carbohydrates: 4.7,
        calories: 28,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста белокочанная тушёная',
        proteins: 2,
        fats: 3.3,
        carbohydrates: 9.2,
        calories: 75,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста брокколи',
        proteins: 2.8,
        fats: 0.4,
        carbohydrates: 6.6,
        calories: 34,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста брюссельская',
        proteins: 4.8,
        fats: 0.3,
        carbohydrates: 3.1,
        calories: 35,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста квашеная',
        proteins: 1.8,
        fats: 0.1,
        carbohydrates: 3,
        calories: 23,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста кольраби',
        proteins: 2.8,
        fats: 0.1,
        carbohydrates: 7.9,
        calories: 44,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста краснокочанная',
        proteins: 0.8,
        fats: 0.2,
        carbohydrates: 5.1,
        calories: 26,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста пекинская',
        proteins: 1.2,
        fats: 0.2,
        carbohydrates: 2,
        calories: 16,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста савойская',
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 6,
        calories: 28,
        category: 'Овощи и зелень',
    },
    {
        name: 'Капуста цветная',
        proteins: 2.5,
        fats: 0.3,
        carbohydrates: 4.2,
        calories: 30,
        category: 'Овощи и зелень',
    },
    {
        name: 'Картофель',
        proteins: 2,
        fats: 0.4,
        carbohydrates: 16.3,
        calories: 77,
        category: 'Овощи и зелень',
    },
    {
        name: 'Картофель жареный',
        proteins: 2.8,
        fats: 9.6,
        carbohydrates: 23.5,
        calories: 192,
        category: 'Овощи и зелень',
    },
    {
        name: 'Каша из тыквы',
        proteins: 2.1,
        fats: 1.7,
        carbohydrates: 15.7,
        calories: 87,
        category: 'Овощи и зелень',
    },
    {
        name: 'Кинза (зелень)',
        proteins: 2.1,
        fats: 0.5,
        carbohydrates: 3.7,
        calories: 23,
        category: 'Овощи и зелень',
    },
    {
        name: 'Кресс-салат (зелень)',
        proteins: 2.6,
        fats: 0.7,
        carbohydrates: 5.5,
        calories: 32,
        category: 'Овощи и зелень',
    },
    {
        name: 'Листья одуванчика (зелень)',
        proteins: 2.7,
        fats: 0.7,
        carbohydrates: 9.2,
        calories: 45,
        category: 'Овощи и зелень',
    },
    {
        name: 'Лук зелёный (перо)',
        proteins: 1.3,
        fats: 0.1,
        carbohydrates: 3.2,
        calories: 20,
        category: 'Овощи и зелень',
    },
    {
        name: 'Лук порей',
        proteins: 2,
        fats: 0.2,
        carbohydrates: 6.3,
        calories: 36,
        category: 'Овощи и зелень',
    },
    {
        name: 'Лук репчатый',
        proteins: 1.4,
        fats: 0.2,
        carbohydrates: 8.2,
        calories: 41,
        category: 'Овощи и зелень',
    },
    {
        name: 'Морковь',
        proteins: 1.3,
        fats: 0.1,
        carbohydrates: 6.9,
        calories: 35,
        category: 'Овощи и зелень',
    },
    {
        name: 'Морковь отварная',
        proteins: 1.3,
        fats: 0.1,
        carbohydrates: 6.4,
        calories: 33,
        category: 'Овощи и зелень',
    },
    {
        name: 'Морская капуста',
        proteins: 0.9,
        fats: 0.2,
        carbohydrates: 3,
        calories: 25,
        category: 'Овощи и зелень',
    },
    {
        name: 'Огурец',
        proteins: 0.8,
        fats: 0.1,
        carbohydrates: 2.5,
        calories: 14,
        category: 'Овощи и зелень',
    },
    {
        name: 'Огурцы солёные',
        proteins: 0.8,
        fats: 0.1,
        carbohydrates: 1.7,
        calories: 13,
        category: 'Овощи и зелень',
    },
    {
        name: 'Папоротник',
        proteins: 4.6,
        fats: 0.4,
        carbohydrates: 5.5,
        calories: 34,
        category: 'Овощи и зелень',
    },
    {
        name: 'Пастернак (корень)',
        proteins: 1.4,
        fats: 0.5,
        carbohydrates: 9.2,
        calories: 47,
        category: 'Овощи и зелень',
    },
    {
        name: 'Перец сладкий (болгарский)',
        proteins: 1.3,
        fats: 0.1,
        carbohydrates: 4.9,
        calories: 26,
        category: 'Овощи и зелень',
    },
    {
        name: 'Петрушка (зелень)',
        proteins: 3.7,
        fats: 0.4,
        carbohydrates: 7.6,
        calories: 49,
        category: 'Овощи и зелень',
    },
    {
        name: 'Петрушка (корень)',
        proteins: 1.5,
        fats: 0.6,
        carbohydrates: 10.1,
        calories: 51,
        category: 'Овощи и зелень',
    },
    {
        name: 'Помидор (томат)',
        proteins: 1.1,
        fats: 0.2,
        carbohydrates: 3.8,
        calories: 24,
        category: 'Овощи и зелень',
    },
    {
        name: 'Ревень (зелень)',
        proteins: 0.7,
        fats: 0.1,
        carbohydrates: 2.5,
        calories: 16,
        category: 'Овощи и зелень',
    },
    {
        name: 'Редис',
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 3.4,
        calories: 20,
        category: 'Овощи и зелень',
    },
    {
        name: 'Редька чёрная',
        proteins: 1.9,
        fats: 0.2,
        carbohydrates: 6.7,
        calories: 36,
        category: 'Овощи и зелень',
    },
    {
        name: 'Репа',
        proteins: 1.5,
        fats: 0.1,
        carbohydrates: 6.2,
        calories: 32,
        category: 'Овощи и зелень',
    },
    {
        name: 'Салат листовой (зелень)',
        proteins: 1.5,
        fats: 0.2,
        carbohydrates: 2,
        calories: 16,
        category: 'Овощи и зелень',
    },
    {
        name: 'Свекла',
        proteins: 1.5,
        fats: 0.1,
        carbohydrates: 8.8,
        calories: 42,
        category: 'Овощи и зелень',
    },
    {
        name: 'Свекла отварная',
        proteins: 1.8,
        fats: 0.1,
        carbohydrates: 9.8,
        calories: 48,
        category: 'Овощи и зелень',
    },
    {
        name: 'Сельдерей (зелень)',
        proteins: 0.9,
        fats: 0.1,
        carbohydrates: 2.1,
        calories: 13,
        category: 'Овощи и зелень',
    },
    {
        name: 'Сельдерей (корень)',
        proteins: 1.3,
        fats: 0.3,
        carbohydrates: 6.5,
        calories: 34,
        category: 'Овощи и зелень',
    },
    {
        name: 'Спаржа (зелень)',
        proteins: 1.9,
        fats: 0.1,
        carbohydrates: 3.1,
        calories: 21,
        category: 'Овощи и зелень',
    },
    {
        name: 'Томатная паста',
        proteins: 4.8,
        fats: 0,
        carbohydrates: 19,
        calories: 102,
        category: 'Овощи и зелень',
    },
    {
        name: 'Топинамбур',
        proteins: 2.1,
        fats: 0.1,
        carbohydrates: 12.8,
        calories: 61,
        category: 'Овощи и зелень',
    },
    {
        name: 'Тыква',
        proteins: 1,
        fats: 0.1,
        carbohydrates: 4.4,
        calories: 22,
        category: 'Овощи и зелень',
    },
    {
        name: 'Тыква отварная',
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 4.9,
        calories: 26,
       category: 'Овощи и зелень',
    },
    {
        name: 'Укроп (зелень)',
        proteins: 2.5,
        fats: 0.5,
        carbohydrates: 6.3,
        calories: 40,
        category: 'Овощи и зелень',
    },
    {
        name: 'Хрен (корень)',
        proteins: 3.2,
        fats: 0.4,
        carbohydrates: 10.5,
        calories: 59,
        category: 'Овощи и зелень',
    },
    {
        name: 'Чеснок',
        proteins: 6.5,
        fats: 0.5,
        carbohydrates: 29.9,
        calories: 149,
        category: 'Овощи и зелень',
    },
    {
        name: 'Шпинат (зелень)',
        proteins: 2.9,
        fats: 0.3,
        carbohydrates: 2,
        calories: 23,
        category: 'Овощи и зелень',
    },
    {
        name: 'Щавель (зелень)',
        proteins: 1.5,
        fats: 0.3,
        carbohydrates: 2.9,
        calories: 22,
        category: 'Овощи и зелень',
    },
    {
        name: 'Абрикос',
        proteins: 0.9,
        fats: 0.1,
        carbohydrates: 9,
        calories: 44,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Авокадо',
        proteins: 2,
        fats: 14.6,
        carbohydrates: 1.8,
        calories: 160,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Айва',
        proteins: 0.6,
        fats: 0.5,
        carbohydrates: 9.6,
        calories: 48,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Алыча',
        proteins: 0.2,
        fats: 0.1,
        carbohydrates: 7.9,
        calories: 34,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Ананас',
        proteins: 0.4,
        fats: 0.2,
        carbohydrates: 11.5,
        calories: 52,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Апельсин',
        proteins: 0.9,
        fats: 0.2,
        carbohydrates: 8.1,
        calories: 43,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Арбуз',
        proteins: 0.6,
        fats: 0.1,
        carbohydrates: 5.8,
        calories: 27,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Банан',
        proteins: 1.5,
        fats: 0.5,
        carbohydrates: 21,
        calories: 96,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Брусника',
        proteins: 0.7,
        fats: 0.5,
        carbohydrates: 8.2,
        calories: 46,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Варенье из клубники',
        proteins: 0.3,
        fats: 0.1,
        carbohydrates: 74,
        calories: 285,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Варенье из малины',
        proteins: 0.6,
        fats: 0.2,
        carbohydrates: 70.4,
        calories: 273,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Виноград',
        proteins: 0.6,
        fats: 0.6,
        carbohydrates: 15.4,
        calories: 72,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Вишня',
        proteins: 0.8,
        fats: 0.2,
        carbohydrates: 10.6,
        calories: 52,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Голубика',
        proteins: 1,
        fats: 0.5,
        carbohydrates: 6.6,
        calories: 39,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Гранат',
        proteins: 0.7,
        fats: 0.6,
        carbohydrates: 14.5,
        calories: 72,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Грейпфрут',
        proteins: 0.7,
        fats: 0.2,
        carbohydrates: 6.5,
        calories: 35,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Груша',
        proteins: 0.4,
        fats: 0.3,
        carbohydrates: 10.3,
        calories: 47,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Дуриан',
        proteins: 1.47,
        fats: 5.3,
        carbohydrates: 27.1,
        calories: 147,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Дыня',
        proteins: 0.6,
        fats: 0.3,
        carbohydrates: 7.4,
        calories: 35,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Ежевика',
        proteins: 1.5,
        fats: 0.5,
        carbohydrates: 4.4,
        calories: 34,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Земляника',
        proteins: 0.8,
        fats: 0.4,
        carbohydrates: 7.5,
        calories: 41,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Инжир свежий',
        proteins: 0.7,
        fats: 0.2,
        carbohydrates: 12,
        calories: 54,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Киви',
        proteins: 0.8,
        fats: 0.4,
        carbohydrates: 8.1,
        calories: 47,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Клюква',
        proteins: 0.5,
        fats: 0.2,
        carbohydrates: 3.7,
        calories: 28,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Крыжовник',
        proteins: 0.7,
        fats: 0.2,
        carbohydrates: 9.1,
        calories: 45,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Лимон',
        proteins: 0.9,
        fats: 0.1,
        carbohydrates: 3,
        calories: 34,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Малина',
        proteins: 0.8,
        fats: 0.5,
        carbohydrates: 8.3,
        calories: 46,
        category: 'Фрукты и ягоды',
    },{
        name: 'Манго',
        proteins: 0.8,
        fats: 0.4,
        carbohydrates: 15,
        calories: 60,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Мандарин',
        proteins: 0.8,
        fats: 0.2,
        carbohydrates: 7.5,
        calories: 38,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Морошка',
        proteins: 0.8,
        fats: 0.9,
        carbohydrates: 7.4,
        calories: 40,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Нектарин',
        proteins: 1.1,
        fats: 0.3,
        carbohydrates: 10.5,
        calories: 44,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Облепиха',
        proteins: 1.2,
        fats: 5.4,
        carbohydrates: 5.7,
        calories: 82,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Папайя',
        proteins: 0.5,
        fats: 0.3,
        carbohydrates: 10.8,
        calories: 43,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Персик',
        proteins: 0.9,
        fats: 0.1,
        carbohydrates: 9.5,
        calories: 45,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Помело',
        proteins: 0.8,
        fats: 0,
        carbohydrates: 9.6,
        calories: 38,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Рябина красная',
        proteins: 1.4,
        fats: 0.2,
        carbohydrates: 8.9,
        calories: 50,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Рябина черноплодная',
        proteins: 1.5,
        fats: 0.2,
        carbohydrates: 10.9,
        calories: 55,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Слива',
        proteins: 0.8,
        fats: 0.3,
        carbohydrates: 9.6,
        calories: 49,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Смородина белая',
        proteins: 0.5,
        fats: 0.2,
        carbohydrates: 8,
        calories: 42,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Смородина красная',
        proteins: 0.6,
        fats: 0.2,
        carbohydrates: 7.7,
        calories: 43,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Смородина чёрная',
        proteins: 1,
        fats: 0.4,
        carbohydrates: 7.3,
        calories: 44,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Фейхоа',
        proteins: 0.7,
        fats: 0.4,
        carbohydrates: 15.2,
        calories: 61,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Хурма',
        proteins: 0.5,
        fats: 0.4,
        carbohydrates: 15.3,
        calories: 67,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Черешня',
        proteins: 1.1,
        fats: 0.4,
        carbohydrates: 10.6,
        calories: 52,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Черника',
        proteins: 1.1,
        fats: 0.6,
        carbohydrates: 7.6,
        calories: 44,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Шиповник',
        proteins: 1.6,
        fats: 0.7,
        carbohydrates: 22.4,
        calories: 109,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Яблоки',
        proteins: 0.4,
        fats: 0.4,
        carbohydrates: 9.8,
        calories: 47,
        category: 'Фрукты и ягоды',
    },
    {
        name: 'Груша сушёная',
        proteins: 2.3,
        fats: 0.6,
        carbohydrates: 62.6,
        calories: 270,
        category: 'Сухофрукты',
    },
    {
        name: 'Изюм',
        proteins: 2.3,
        fats: 0.5,
        carbohydrates: 65.8,
        calories: 281,
        category: 'Сухофрукты',
    },
    {
        name: 'Инжир сушёный',
        proteins: 3.1,
        fats: 0.8,
        carbohydrates: 57.9,
        calories: 257,
        category: 'Сухофрукты',
    },
    {
        name: 'Курага',
        proteins: 5.2,
        fats: 0.3,
        carbohydrates: 51,
        calories: 232,
        category: 'Сухофрукты',
    },
    {
        name: 'Персик сушёный',
        proteins: 3,
        fats: 0.4,
        carbohydrates: 57.7,
        calories: 254,
        category: 'Сухофрукты',
    },
    {
        name: 'Урюк',
        proteins: 5,
        fats: 0.4,
        carbohydrates: 53,
        calories: 242,
        category: 'Сухофрукты',
    },
    {
        name: 'Финики',
        proteins: 2.5,
        fats: 0.5,
        carbohydrates: 69.2,
        calories: 292,
        category: 'Сухофрукты',
    },
    {
        name: 'Чернослив',
        proteins: 2.3,
        fats: 0.7,
        carbohydrates: 57.5,
        calories: 256,
        category: 'Сухофрукты',
    },
    {
        name: 'Яблоки сушёные',
        proteins: 2.2,
        fats: 0.1,
        carbohydrates: 59,
        calories: 253,
        category: 'Сухофрукты',
    },
    {
        name: 'Гриб вешенка',
        proteins: 3.3,
        fats: 0.4,
        carbohydrates: 6.1,
        calories: 33,
        category: 'Грибы',
    },
    {
        name: 'Гриб рыжик',
        proteins: 1.9,
        fats: 0.8,
        carbohydrates: 0.5,
        calories: 17,
        category: 'Грибы',
    },
    {
        name: 'Гриб сморчок',
        proteins: 3.1,
        fats: 0.6,
        carbohydrates: 5.1,
        calories: 31,
        category: 'Грибы',
    },
    {
        name: 'Грибы белые',
        proteins: 3.7,
        fats: 1.7,
        carbohydrates: 1.1,
        calories: 34,
        category: 'Грибы',
    },
    {
        name: 'Грибы белые сушёные',
        proteins: 30.3,
        fats: 14.3,
        carbohydrates: 9,
        calories: 286,
        category: 'Грибы',
    },
    {
        name: 'Грибы лисички',
        proteins: 1.5,
        fats: 1,
        carbohydrates: 1,
        calories: 19,
        category: 'Грибы',
    },
    {
        name: 'Грибы опята',
        proteins: 2.2,
        fats: 1.2,
        carbohydrates: 0.5,
        calories: 22,
        category: 'Грибы',
    },
    {
        name: 'Грибы подберёзовики',
        proteins: 2.1,
        fats: 0.8,
        carbohydrates: 1.2,
        calories: 20,
        category: 'Грибы',
    },
    {
        name: 'Грибы подосиновики',
        proteins: 3.3,
        fats: 0.5,
        carbohydrates: 1.2,
        calories: 22,
        category: 'Грибы',
    },
    {
        name: 'Грибы сыроежки',
        proteins: 1.7,
        fats: 0.7,
        carbohydrates: 1.5,
        calories: 19,
        category: 'Грибы',
    },
    {
        name: 'Грибы шампиньоны',
        proteins: 4.3,
        fats: 1,
        carbohydrates: 0.1,
        calories: 27,
        category: 'Грибы',
    },
    {
        name: 'Грибы шиитаке',
        proteins: 2.2,
        fats: 0.5,
        carbohydrates: 6.8,
        calories: 34,
        category: 'Грибы',
    },
    {
        name: 'Сок абрикосовый',
        proteins: 0.5,
        fats: 0,
        carbohydrates: 12.7,
        calories: 55,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок ананасовый',
        proteins: 0.3,
        fats: 0.1,
        carbohydrates: 11.8,
        calories: 52,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок апельсиновый',
        proteins: 0.7,
        fats: 0.2,
        carbohydrates: 10.4,
        calories: 45,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок виноградный',
        proteins: 0.3,
        fats: 0.2,
        carbohydrates: 16.3,
        calories: 70,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок вишнёвый',
        proteins: 0.7,
        fats: 0.2,
        carbohydrates: 11.4,
        calories: 51,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок гранатовый',
        proteins: 0.3,
        fats: 0.1,
        carbohydrates: 14.2,
        calories: 56,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок грейпфрутовый',
        proteins: 0.3,
        fats: 0.1,
        carbohydrates: 7.9,
        calories: 38,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок капустный',
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 7.1,
        calories: 33,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок лимонный',
        proteins: 0.3,
        fats: 0.2,
        carbohydrates: 6.9,
        calories: 22,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок мандариновый',
        proteins: 0.8,
        fats: 0,
        carbohydrates: 9.8,
        calories: 45,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок морковный',
        proteins: 1.1,
        fats: 0.1,
        carbohydrates: 12.6,
        calories: 56,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок персиковый',
        proteins: 0.3,
        fats: 0,
        carbohydrates: 16.5,
        calories: 68,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок свекольный',
        proteins: 1,
        fats: 0,
        carbohydrates: 14,
        calories: 61,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок томатный',
        proteins: 1,
        fats: 0.1,
        carbohydrates: 2.9,
        calories: 18,
        category: 'Фруктовые и овощные соки',
    },
    {
        name: 'Сок яблочный',
        proteins: 0.5,
        fats: 0.1,
        carbohydrates: 10.1,
        calories: 46,
        category: 'Фруктовые и овощные соки',
    },
    
];

// console.log(document.getElementById('categories').value)

function sortByField(field) {
    products.sort((a, b) => a[field] > b[field] ? 1 : -1);
}

function sortOfName() {
    sortByField('name')
    render();
}

function sortOfProteins() {
    sortByField('proteins')
    render();
}

function sortOfFats() {
    sortByField('fats')
    render();
}

function sortOfCarbohydrates() {
    sortByField('carbohydrates')
    render();
}

function sortOfCalories() {
    sortByField('calories')
    render();
}

function render() {
    document.getElementById('calories_table').innerHTML=``
    for (product of products) {
        document.getElementById('calories_table').innerHTML+=`
        <tr>
                    <td id="name">${product.name}</td>
                    <td id="proteins">${product.proteins}</td>
                    <td id="fats">${product.fats}</td>
                    <td id="carbohydrates">${product.carbohydrates}</td>
                    <td id="calories">${product.calories}</td>
                </tr>
        `
    }
}

function change() {
    let input = document.getElementById('search').value
    input = input.toLowerCase();
    document.getElementById('calories_table').innerHTML=``;
    for (product of products) {
        if (product.name.toLowerCase().includes(input)) {
            document.getElementById('calories_table').innerHTML+=`
        <tr>
                    <td id="name">${product.name}</td>
                    <td id="proteins">${product.proteins}</td>
                    <td id="fats">${product.fats}</td>
                    <td id="carbohydrates">${product.carbohydrates}</td>
                    <td id="calories">${product.calories}</td>
                </tr>
        `
        }
    }
}

function findOption(select) {
    let option = select.querySelector(`option[value="${select.value}"]`);
    option = option.innerHTML;
    sortOfCategory(option);
}

function sortOfCategory(option) {
    document.getElementById('calories_table').innerHTML=``;
    for (product of products) {
        if (product.category == option) {
            document.getElementById('calories_table').innerHTML+=`
        <tr>
                    <td id="name">${product.name}</td>
                    <td id="proteins">${product.proteins}</td>
                    <td id="fats">${product.fats}</td>
                    <td id="carbohydrates">${product.carbohydrates}</td>
                    <td id="calories">${product.calories}</td>
                </tr>
        `
        }else if(option == 'Все категории') {
            render();
        }
    }
}